import json, urllib.request

req_get = urllib.request.Request(
    'http://127.0.0.1:7700/indexes/services/settings/synonyms',
    method='GET',
    headers={'Authorization': 'Bearer acad64db686c48a6cca1578b0ecdcea3938fa6653377fc00b3868e58beeed554'}
)
with urllib.request.urlopen(req_get) as r:
    current = json.loads(r.read().decode())

# Транслитерация латиницей → русский
translit = {
    "vrach": ["врач", "доктор", "медик"],
    "doktor": ["врач", "доктор", "медик"],
    "medik": ["врач", "доктор", "медик"],
    "stomatolog": ["стоматолог", "дантист", "зубной"],
    "dentist": ["стоматолог", "дантист", "зубной"],
    "pediatr": ["педиатр", "детский врач"],
    "ginekolog": ["гинеколог"],
    "kardiolog": ["кардиолог"],
    "nevrolog": ["невролог", "невропатолог"],
    "oftalmolog": ["офтальмолог", "окулист"],
    "okulist": ["офтальмолог", "окулист"],
    "dermatolog": ["дерматолог"],
    "hirurg": ["хирург"],
    "ortoped": ["ортопед"],
    "psiholog": ["психолог", "психотерапевт"],
    "psycholog": ["психолог", "психотерапевт"],
    "massazhist": ["массажист", "массаж"],
    "massage": ["массаж", "массажист"],
    "masseur": ["массажист", "массаж"],
    "kosmetolog": ["косметолог"],
    "dietolog": ["диетолог"],
    "logoped": ["логопед"],
    "osteopat": ["остеопат"],
    "parikmakher": ["парикмахер", "барбер", "стилист"],
    "barber": ["барбер", "парикмахер", "стилист"],
    "manikyur": ["маникюр", "ногти"],
    "pedikyur": ["педикюр"],
    "yurist": ["юрист", "адвокат", "правовед"],
    "advokat": ["адвокат", "юрист", "правовед"],
    "lawyer": ["юрист", "адвокат"],
    "avocat": ["юрист", "адвокат"],
    "notarius": ["нотариус"],
    "notaire": ["нотариус"],
    "repetitor": ["репетитор", "учитель", "преподаватель"],
    "tutor": ["репетитор", "учитель"],
    "uchitel": ["учитель", "репетитор", "преподаватель"],
    "buhgalter": ["бухгалтер", "финансист"],
    "accountant": ["бухгалтер", "финансист"],
    "comptable": ["бухгалтер"],
    "perevodchik": ["переводчик"],
    "translator": ["переводчик"],
    "traducteur": ["переводчик"],
    "nanya": ["няня"],
    "babysitter": ["няня"],
    "nounou": ["няня"],
    "santehnik": ["сантехник"],
    "plumber": ["сантехник"],
    "plombier": ["сантехник"],
    "elektrik": ["электрик"],
    "electrician": ["электрик"],
    "stroitel": ["строитель"],
    "malyar": ["маляр"],
    "painter": ["маляр"],
    "plotnik": ["плотник"],
    "carpenter": ["плотник"],
    "rieltor": ["риелтор", "агент по недвижимости"],
    "gruzchik": ["грузчик", "переезд", "перевозка"],
    "mover": ["грузчик", "переезд"],
    "perevozki": ["перевозки", "перевозка", "переезд", "грузчик"],
    "perevozka": ["перевозка", "перевозки", "переезд"],
    "pereezd": ["переезд", "перевозка", "грузчик"],
    "transport": ["перевозка", "перевозки", "транспорт"],
    "taksi": ["такси"],
    "taxi": ["такси"],
    "voditel": ["водитель", "такси", "шофер"],
    "shofer": ["шофер", "водитель", "такси"],
    "chauffeur": ["водитель", "шофер", "такси"],
    "programmist": ["программист", "разработчик"],
    "developer": ["разработчик", "программист"],
    "dizainer": ["дизайнер"],
    "designer": ["дизайнер"],
    "fotograf": ["фотограф"],
    "photographer": ["фотограф"],
    "videograf": ["видеограф"],
    "uborka": ["уборка", "клининг"],
    "cleaning": ["уборка", "клининг"],
    "klinig": ["клининг", "уборка"],
    "sadovnik": ["садовник"],
    "jardinier": ["садовник"],
    "gardener": ["садовник"],
    "strahovanie": ["страхование", "страховка"],
    "insurance": ["страхование", "страховка"],
    "assurance": ["страхование", "страховка"],
    "biznes": ["бизнес"],
    "business": ["бизнес"],
    "dostavka": ["доставка"],
    "delivery": ["доставка"],
    "remont": ["ремонт"],
    "stylist": ["стилист", "парикмахер"],
    "coiffeur": ["парикмахер", "стилист"],
    "hairdresser": ["парикмахер", "стилист"],
}

current.update(translit)

data = json.dumps(current, ensure_ascii=False).encode('utf-8')
req_put = urllib.request.Request(
    'http://127.0.0.1:7700/indexes/services/settings/synonyms',
    data=data,
    method='PUT',
    headers={
        'Content-Type': 'application/json',
        'Authorization': 'Bearer acad64db686c48a6cca1578b0ecdcea3938fa6653377fc00b3868e58beeed554'
    }
)
with urllib.request.urlopen(req_put) as r:
    print('OK:', r.read().decode())
